name: Java CI with Maven and CD on Tomcat
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: rsync deployment
      uses: D3rHase/rsync-deploy-action@v0.2
      with:
        HOST: ${{ secrets.HOST }}
        PORT: ${{ secrets.PORT }}
        USER: ${{ secrets.USER }}
        PRIVATE_SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REPOSITORY_PATH: target/*
        SERVER_PATH: /opt/tomcat/webapps
